on: workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
    - name: install bun
      run: curl -fsSL https://bun.sh/install | bash
    - name: Load bun
      run: source /home/runner/.bashrc 
    - name: install dependencies
      run: bun install
    - name: start db
      run: bun ./src/back/manageDatabase.ts
    - name: start front
      run: bun run dev
